#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Eslint checker start running....'

# Run linter
yarn run lint-staged ||
(
   echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Linter Check Failed. Run npm run eslint to check, add changes and try commit again.';
    false;
)

# If everything passes...
echo '✅✅✅✅ You win this time... Committing this now. ✅✅✅✅'
